[package]
name = "rusty_lua"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.1", features = ["lua54", "vendored", "serialize", "macros"] }
serde = { version = "1.0.215", features = ["derive"] }
